ex1:
	gcc ex1.c -o output_ex1
	./output_ex1

ex2:	
	gcc ex2.c -o output_ex2
	./output_ex2

ex3:	
	gcc ex3.c -o output_ex3
	./output_ex3 ex3_binary_file.bin

ex4:	
	gcc ex4.c parser.c -o output_ex4
	./output_ex4 -v 1 -l 8 -t 17 -s 123 -d 83 -p 0 -e 0